GET http://localhost:4000/me

###

GET http://localhost:4000/heroes

###


GET http://localhost:4000/heroes/69

###


GET http://localhost:4000/heroes/bio/60e459571f6ee8329c627e71

###

DELETE  http://localhost:4000/heroes/bio/60e467d6fb4e3730c8b30074

###
GET http://localhost:4000/heroes/60e451e76fbef212f8937d59

###

POST http://localhost:4000/heroes
Content-Type: application/json

{
"id": "69",
      "name": "Batman",
      "powerstats": {
        "intelligence": "81",
        "strength": "40",
        "speed": "29",
        "durability": "55",
        "power": "63",
        "combat": "90"
      },
      "biography": {
        "full-name": "Terry McGinnis",
        "alter-egos": "No alter egos found.",
        "aliases": [
          "Batman II",
          "The Tomorrow Knight",
          "The second Dark Knight",
          "The Dark Knight of Tomorrow",
          "Batman Beyond"
        ],
        "place-of-birth": "Gotham City, 25th Century",
        "first-appearance": "Batman Beyond #1",
        "publisher": "DC Comics",
        "alignment": "good"
      }
}

###
PATCH http://localhost:4000/heroes/60e46d77e07e520870b6d446
Content-Type: application/json

{
  "biography.full-name":"Bruce Wayne3"
  }
