GET http://localhost:4000/me

###

GET http://localhost:4000/heroes

###


GET http://localhost:4000/heroes/69

###


GET http://localhost:4000/heroes/bio/60e804156b6fdc45908b254e

###

DELETE  http://localhost:4000/heroes/bio/60e467d6fb4e3730c8b30074

###
GET http://localhost:4000/heroes

###

POST http://localhost:4000/heroes
Content-Type: application/json

{
"id": "81",
      "name": "Thor",
      "powerstats": {
        "intelligence": "81",
        "strength": "40",
        "speed": "29",
        "durability": "55",
        "power": "63",
        "combat": "90"
      },
      "biography": {
        "full-name": "Terry McGinnis",
        "alter-egos": "No alter egos found.",
        "aliases": [
          "Batman II",
          "The Tomorrow Knight",
          "The second Dark Knight",
          "The Dark Knight of Tomorrow",
          "Batman Beyond"
        ],
        "place-of-birth": "Gotham City, 25th Century",
        "first-appearance": "Batman Beyond #1",
        "publisher": "DC Comics",
        "alignment": "good"
      }
}

###
PATCH http://localhost:4000/heroes/60e46d77e07e520870b6d446
Content-Type: application/json

{
  "biography.full-name":"Bruce Wayne3"
  }



###
GET http://localhost:4000/users

###

POST http://localhost:4000/users
Content-Type: application/json

{
"email": "toto@gmail.com",
"password": "motdepasse",
"role":"user"}

###

POST http://localhost:4000/users
Content-Type: application/json

{
"email": "titi@gmail.com",
"password": "titimotdepasse",
"role":"admin"}

###
GET http://localhost:4000/users/60e5af60d2e6e81fd4ae1b2a

###
PATCH http://localhost:4000/users/60e5b641e01f560b00fa3db7
Content-Type: application/json

{
  "email":"tata@gmail.com"
  }



###

DELETE  http://localhost:4000/users/60e5b649e01f560b00fa3db8


###
POST http://localhost:4000/login
content-type:Application/application/json

{
"email":"titi@gmail.com",
"password":"titimotdepasse"
}

###
GET http://localhost:4000/protected
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZTZmNTgwMjQzNWE4MjA5MDg4NjBhNiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTYyNTc1MzYzNH0.UoNtmdgZlyXdDpSlrbdjHbYW-NVIF9w56OyezZkIGqY